---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: git-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: nfs-client
